apiVersion: v1
kind: Pod
metadata:
      name: nginx-app 
      labels:
        app: nginx-app


spec:
      containers:
        - name: nginx-web
          image: nginx
          ports:
              - name: nginxport
                containerPort: 80  


