---
- hosts: kubernetes
  user: root
  tasks:
      - name: deploy regapp on kubernetes
        command: kubectl apply -f regapp-deployment.yml

      - name: create service for regapp NodePort
        command: kubectl apply -f regapp-service.yml

      - name: To rolling update
        command: kubectl rollout restart deployment.apps/deployment-regapp